# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classify_pb2 as classify__pb2


class ClassifyStub(object):
  """Service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Parse = channel.unary_unary(
        '/classify.Classify/Parse',
        request_serializer=classify__pb2.UserFeatures.SerializeToString,
        response_deserializer=classify__pb2.UserClass.FromString,
        )


class ClassifyServicer(object):
  """Service definition
  """

  def Parse(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClassifyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Parse': grpc.unary_unary_rpc_method_handler(
          servicer.Parse,
          request_deserializer=classify__pb2.UserFeatures.FromString,
          response_serializer=classify__pb2.UserClass.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'classify.Classify', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
